source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               icon.png,\
               icon.svg,\
               SparkUnpivotNodeFactory.xml
